# Site settings
title:          Eyowo
shortname:      Eyowo
company:        Softcom LTD
description:    >-
  Payments, Anytime, Anywhere
url:            'http://app.eyowo.com'
charset:        'UTF-8'
timezone:       Africa/Lagos


# Included Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate


# Build settings
markdown:       kramdown
permalink:      pretty


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - dev
  - .gitignore